<?php

namespace Database\Seeders;

use App\Models\Badge;
use Illuminate\Database\Seeder;

class BadgeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $badges = [
            // ========================================
            // MILESTONE BADGES - Token Milestones
            // ========================================
            [
                'slug' => 'tokens-100k',
                'name' => 'Token Taster',
                'description' => 'Process your first 100,000 tokens',
                'category' => Badge::CATEGORY_MILESTONE,
                'tier' => 1,
                'icon' => 'sparkles',
                'is_hidden' => false,
                'requirements' => ['type' => 'total_tokens', 'threshold' => 100_000],
                'sort_order' => 100,
            ],
            [
                'slug' => 'tokens-250k',
                'name' => 'Token Trainee',
                'description' => 'Process 250,000 tokens',
                'category' => Badge::CATEGORY_MILESTONE,
                'tier' => 1,
                'icon' => 'sparkles',
                'is_hidden' => false,
                'requirements' => ['type' => 'total_tokens', 'threshold' => 250_000],
                'sort_order' => 101,
            ],
            [
                'slug' => 'tokens-500k',
                'name' => 'Token Apprentice',
                'description' => 'Process 500,000 tokens',
                'category' => Badge::CATEGORY_MILESTONE,
                'tier' => 1,
                'icon' => 'sparkles',
                'is_hidden' => false,
                'requirements' => ['type' => 'total_tokens', 'threshold' => 500_000],
                'sort_order' => 102,
            ],
            [
                'slug' => 'tokens-1m',
                'name' => 'Millionaire',
                'description' => 'Process 1 million tokens',
                'category' => Badge::CATEGORY_MILESTONE,
                'tier' => 2,
                'icon' => 'fire',
                'is_hidden' => false,
                'requirements' => ['type' => 'total_tokens', 'threshold' => 1_000_000],
                'sort_order' => 103,
            ],
            [
                'slug' => 'tokens-5m',
                'name' => 'Token Veteran',
                'description' => 'Process 5 million tokens',
                'category' => Badge::CATEGORY_MILESTONE,
                'tier' => 2,
                'icon' => 'fire',
                'is_hidden' => false,
                'requirements' => ['type' => 'total_tokens', 'threshold' => 5_000_000],
                'sort_order' => 104,
            ],
            [
                'slug' => 'tokens-10m',
                'name' => 'Token Master',
                'description' => 'Process 10 million tokens',
                'category' => Badge::CATEGORY_MILESTONE,
                'tier' => 2,
                'icon' => 'fire',
                'is_hidden' => false,
                'requirements' => ['type' => 'total_tokens', 'threshold' => 10_000_000],
                'sort_order' => 105,
            ],
            [
                'slug' => 'tokens-25m',
                'name' => 'Token Legend',
                'description' => 'Process 25 million tokens',
                'category' => Badge::CATEGORY_MILESTONE,
                'tier' => 3,
                'icon' => 'bolt',
                'is_hidden' => false,
                'requirements' => ['type' => 'total_tokens', 'threshold' => 25_000_000],
                'sort_order' => 106,
            ],
            [
                'slug' => 'tokens-50m',
                'name' => 'Token Titan',
                'description' => 'Process 50 million tokens',
                'category' => Badge::CATEGORY_MILESTONE,
                'tier' => 3,
                'icon' => 'bolt',
                'is_hidden' => false,
                'requirements' => ['type' => 'total_tokens', 'threshold' => 50_000_000],
                'sort_order' => 107,
            ],
            [
                'slug' => 'tokens-100m',
                'name' => 'Centurion',
                'description' => 'Process 100 million tokens',
                'category' => Badge::CATEGORY_MILESTONE,
                'tier' => 3,
                'icon' => 'bolt',
                'is_hidden' => false,
                'requirements' => ['type' => 'total_tokens', 'threshold' => 100_000_000],
                'sort_order' => 108,
            ],
            [
                'slug' => 'tokens-250m',
                'name' => 'Quarter Billionaire',
                'description' => 'Process 250 million tokens',
                'category' => Badge::CATEGORY_MILESTONE,
                'tier' => 4,
                'icon' => 'crown',
                'is_hidden' => false,
                'requirements' => ['type' => 'total_tokens', 'threshold' => 250_000_000],
                'sort_order' => 109,
            ],
            [
                'slug' => 'tokens-500m',
                'name' => 'Half Billionaire',
                'description' => 'Process 500 million tokens',
                'category' => Badge::CATEGORY_MILESTONE,
                'tier' => 4,
                'icon' => 'crown',
                'is_hidden' => false,
                'requirements' => ['type' => 'total_tokens', 'threshold' => 500_000_000],
                'sort_order' => 110,
            ],
            [
                'slug' => 'tokens-1b',
                'name' => 'Billionaire',
                'description' => 'Process 1 billion tokens',
                'category' => Badge::CATEGORY_MILESTONE,
                'tier' => 5,
                'icon' => 'trophy',
                'is_hidden' => false,
                'requirements' => ['type' => 'total_tokens', 'threshold' => 1_000_000_000],
                'sort_order' => 111,
            ],

            // ========================================
            // MILESTONE BADGES - Cost Milestones
            // ========================================
            [
                'slug' => 'cost-1',
                'name' => 'First Dollar',
                'description' => 'Spend your first $1 on AI',
                'category' => Badge::CATEGORY_MILESTONE,
                'tier' => 1,
                'icon' => 'currency-dollar',
                'is_hidden' => false,
                'requirements' => ['type' => 'total_cost', 'threshold' => 1],
                'sort_order' => 150,
            ],
            [
                'slug' => 'cost-10',
                'name' => 'Ten Spot',
                'description' => 'Spend $10 on AI',
                'category' => Badge::CATEGORY_MILESTONE,
                'tier' => 1,
                'icon' => 'currency-dollar',
                'is_hidden' => false,
                'requirements' => ['type' => 'total_cost', 'threshold' => 10],
                'sort_order' => 151,
            ],
            [
                'slug' => 'cost-50',
                'name' => 'Fifty Club',
                'description' => 'Spend $50 on AI',
                'category' => Badge::CATEGORY_MILESTONE,
                'tier' => 2,
                'icon' => 'currency-dollar',
                'is_hidden' => false,
                'requirements' => ['type' => 'total_cost', 'threshold' => 50],
                'sort_order' => 152,
            ],
            [
                'slug' => 'cost-100',
                'name' => 'Benjamin',
                'description' => 'Spend $100 on AI',
                'category' => Badge::CATEGORY_MILESTONE,
                'tier' => 2,
                'icon' => 'banknotes',
                'is_hidden' => false,
                'requirements' => ['type' => 'total_cost', 'threshold' => 100],
                'sort_order' => 153,
            ],
            [
                'slug' => 'cost-500',
                'name' => 'High Roller',
                'description' => 'Spend $500 on AI',
                'category' => Badge::CATEGORY_MILESTONE,
                'tier' => 3,
                'icon' => 'banknotes',
                'is_hidden' => false,
                'requirements' => ['type' => 'total_cost', 'threshold' => 500],
                'sort_order' => 154,
            ],
            [
                'slug' => 'cost-1000',
                'name' => 'Grand Master',
                'description' => 'Spend $1,000 on AI',
                'category' => Badge::CATEGORY_MILESTONE,
                'tier' => 4,
                'icon' => 'banknotes',
                'is_hidden' => false,
                'requirements' => ['type' => 'total_cost', 'threshold' => 1000],
                'sort_order' => 155,
            ],
            [
                'slug' => 'cost-5000',
                'name' => 'Whale',
                'description' => 'Spend $5,000 on AI',
                'category' => Badge::CATEGORY_MILESTONE,
                'tier' => 5,
                'icon' => 'banknotes',
                'is_hidden' => false,
                'requirements' => ['type' => 'total_cost', 'threshold' => 5000],
                'sort_order' => 156,
            ],

            // ========================================
            // EFFICIENCY BADGES - Cache Rate
            // ========================================
            [
                'slug' => 'cache-apprentice',
                'name' => 'Cache Apprentice',
                'description' => 'Achieve 25% cache hit rate',
                'category' => Badge::CATEGORY_EFFICIENCY,
                'tier' => 1,
                'icon' => 'archive-box',
                'is_hidden' => false,
                'requirements' => ['type' => 'cache_rate', 'threshold' => 25],
                'sort_order' => 200,
            ],
            [
                'slug' => 'cache-master',
                'name' => 'Cache Master',
                'description' => 'Achieve 50% cache hit rate',
                'category' => Badge::CATEGORY_EFFICIENCY,
                'tier' => 2,
                'icon' => 'archive-box',
                'is_hidden' => false,
                'requirements' => ['type' => 'cache_rate', 'threshold' => 50],
                'sort_order' => 201,
            ],
            [
                'slug' => 'cache-lord',
                'name' => 'Cache Lord',
                'description' => 'Achieve 75% cache hit rate - master of efficiency',
                'category' => Badge::CATEGORY_EFFICIENCY,
                'tier' => 3,
                'icon' => 'archive-box-arrow-down',
                'is_hidden' => false,
                'requirements' => ['type' => 'cache_rate', 'threshold' => 75],
                'sort_order' => 202,
            ],

            // ========================================
            // STREAK BADGES
            // ========================================
            [
                'slug' => 'streak-3',
                'name' => 'Three-Peat',
                'description' => 'Code with AI for 3 consecutive days',
                'category' => Badge::CATEGORY_STREAK,
                'tier' => 1,
                'icon' => 'fire',
                'is_hidden' => false,
                'requirements' => ['type' => 'current_streak', 'threshold' => 3],
                'sort_order' => 300,
            ],
            [
                'slug' => 'streak-7',
                'name' => 'Week Warrior',
                'description' => 'Code with AI for 7 consecutive days',
                'category' => Badge::CATEGORY_STREAK,
                'tier' => 2,
                'icon' => 'fire',
                'is_hidden' => false,
                'requirements' => ['type' => 'current_streak', 'threshold' => 7],
                'sort_order' => 301,
            ],
            [
                'slug' => 'streak-14',
                'name' => 'Fortnight Force',
                'description' => 'Code with AI for 14 consecutive days',
                'category' => Badge::CATEGORY_STREAK,
                'tier' => 2,
                'icon' => 'fire',
                'is_hidden' => false,
                'requirements' => ['type' => 'current_streak', 'threshold' => 14],
                'sort_order' => 302,
            ],
            [
                'slug' => 'streak-30',
                'name' => 'Monthly Machine',
                'description' => 'Code with AI for 30 consecutive days',
                'category' => Badge::CATEGORY_STREAK,
                'tier' => 3,
                'icon' => 'fire',
                'is_hidden' => false,
                'requirements' => ['type' => 'current_streak', 'threshold' => 30],
                'sort_order' => 303,
            ],
            [
                'slug' => 'streak-60',
                'name' => 'Sixty-Day Sage',
                'description' => 'Code with AI for 60 consecutive days',
                'category' => Badge::CATEGORY_STREAK,
                'tier' => 4,
                'icon' => 'fire',
                'is_hidden' => false,
                'requirements' => ['type' => 'current_streak', 'threshold' => 60],
                'sort_order' => 304,
            ],
            [
                'slug' => 'streak-100',
                'name' => 'Century Club',
                'description' => 'Code with AI for 100 consecutive days',
                'category' => Badge::CATEGORY_STREAK,
                'tier' => 5,
                'icon' => 'fire',
                'is_hidden' => false,
                'requirements' => ['type' => 'current_streak', 'threshold' => 100],
                'sort_order' => 305,
            ],

            // ========================================
            // TIME-BASED BADGES
            // ========================================
            [
                'slug' => 'night-owl',
                'name' => 'Night Owl',
                'description' => 'Complete 10 coding sessions between 10pm and 4am',
                'category' => Badge::CATEGORY_TIME,
                'tier' => 2,
                'icon' => 'moon',
                'is_hidden' => false,
                'requirements' => ['type' => 'night_sessions', 'threshold' => 10],
                'sort_order' => 400,
            ],
            [
                'slug' => 'early-bird',
                'name' => 'Early Bird',
                'description' => 'Complete 10 coding sessions between 5am and 7am',
                'category' => Badge::CATEGORY_TIME,
                'tier' => 2,
                'icon' => 'sun',
                'is_hidden' => false,
                'requirements' => ['type' => 'early_sessions', 'threshold' => 10],
                'sort_order' => 401,
            ],
            [
                'slug' => 'weekend-warrior',
                'name' => 'Weekend Warrior',
                'description' => 'Complete 20 coding sessions on weekends',
                'category' => Badge::CATEGORY_TIME,
                'tier' => 2,
                'icon' => 'calendar',
                'is_hidden' => false,
                'requirements' => ['type' => 'weekend_sessions', 'threshold' => 20],
                'sort_order' => 402,
            ],

            // ========================================
            // COMPETITIVE BADGES
            // ========================================
            [
                'slug' => 'weekly-champion',
                'name' => 'Weekly Champion',
                'description' => 'Reach #1 on the weekly leaderboard',
                'category' => Badge::CATEGORY_COMPETITIVE,
                'tier' => 3,
                'icon' => 'trophy',
                'is_hidden' => false,
                'requirements' => ['type' => 'leaderboard_position', 'position' => 1, 'period' => 'week'],
                'sort_order' => 500,
            ],
            [
                'slug' => 'monthly-champion',
                'name' => 'Monthly Champion',
                'description' => 'Reach #1 on the monthly leaderboard',
                'category' => Badge::CATEGORY_COMPETITIVE,
                'tier' => 4,
                'icon' => 'trophy',
                'is_hidden' => false,
                'requirements' => ['type' => 'leaderboard_position', 'position' => 1, 'period' => 'month'],
                'sort_order' => 501,
            ],
            [
                'slug' => 'all-time-champion',
                'name' => 'All-Time Champion',
                'description' => 'Reach #1 on the all-time leaderboard',
                'category' => Badge::CATEGORY_COMPETITIVE,
                'tier' => 5,
                'icon' => 'trophy',
                'is_hidden' => false,
                'requirements' => ['type' => 'leaderboard_position', 'position' => 1, 'period' => 'all'],
                'sort_order' => 502,
            ],
            [
                'slug' => 'hold-1h',
                'name' => 'Hour of Power',
                'description' => 'Hold #1 position for a total of 1 hour',
                'category' => Badge::CATEGORY_COMPETITIVE,
                'tier' => 2,
                'icon' => 'clock',
                'is_hidden' => false,
                'requirements' => ['type' => 'leaderboard_hold_time', 'position' => 1, 'period' => 'all', 'min_duration_ms' => 3_600_000],
                'sort_order' => 510,
            ],
            [
                'slug' => 'hold-24h',
                'name' => 'Day Dominator',
                'description' => 'Hold #1 position for a total of 24 hours',
                'category' => Badge::CATEGORY_COMPETITIVE,
                'tier' => 3,
                'icon' => 'clock',
                'is_hidden' => false,
                'requirements' => ['type' => 'leaderboard_hold_time', 'position' => 1, 'period' => 'all', 'min_duration_ms' => 86_400_000],
                'sort_order' => 511,
            ],
            [
                'slug' => 'hold-1w',
                'name' => 'Week Warden',
                'description' => 'Hold #1 position for a total of 1 week',
                'category' => Badge::CATEGORY_COMPETITIVE,
                'tier' => 4,
                'icon' => 'clock',
                'is_hidden' => false,
                'requirements' => ['type' => 'leaderboard_hold_time', 'position' => 1, 'period' => 'all', 'min_duration_ms' => 604_800_000],
                'sort_order' => 512,
            ],

            // ========================================
            // CODE PRODUCTIVITY BADGES
            // ========================================
            [
                'slug' => 'surgeon',
                'name' => 'Code Surgeon',
                'description' => 'Remove more code than you add (1,000+ lines removed)',
                'category' => Badge::CATEGORY_EFFICIENCY,
                'tier' => 3,
                'icon' => 'scissors',
                'is_hidden' => false,
                'requirements' => ['type' => 'net_negative_lines', 'min_removed' => 1000],
                'sort_order' => 220,
            ],
            [
                'slug' => 'commits-10',
                'name' => 'Committer',
                'description' => 'Make 10 commits with AI assistance',
                'category' => Badge::CATEGORY_MILESTONE,
                'tier' => 1,
                'icon' => 'arrow-up-circle',
                'is_hidden' => false,
                'requirements' => ['type' => 'total_commits', 'threshold' => 10],
                'sort_order' => 170,
            ],
            [
                'slug' => 'commits-50',
                'name' => 'Commit Commander',
                'description' => 'Make 50 commits with AI assistance',
                'category' => Badge::CATEGORY_MILESTONE,
                'tier' => 2,
                'icon' => 'arrow-up-circle',
                'is_hidden' => false,
                'requirements' => ['type' => 'total_commits', 'threshold' => 50],
                'sort_order' => 171,
            ],
            [
                'slug' => 'commits-100',
                'name' => 'Centurion Committer',
                'description' => 'Make 100 commits with AI assistance',
                'category' => Badge::CATEGORY_MILESTONE,
                'tier' => 3,
                'icon' => 'arrow-up-circle',
                'is_hidden' => false,
                'requirements' => ['type' => 'total_commits', 'threshold' => 100],
                'sort_order' => 172,
            ],
            [
                'slug' => 'pr-1',
                'name' => 'First PR',
                'description' => 'Create your first pull request with AI',
                'category' => Badge::CATEGORY_MILESTONE,
                'tier' => 1,
                'icon' => 'code-bracket',
                'is_hidden' => false,
                'requirements' => ['type' => 'total_pull_requests', 'threshold' => 1],
                'sort_order' => 180,
            ],
            [
                'slug' => 'pr-10',
                'name' => 'PR Pro',
                'description' => 'Create 10 pull requests with AI',
                'category' => Badge::CATEGORY_MILESTONE,
                'tier' => 2,
                'icon' => 'code-bracket',
                'is_hidden' => false,
                'requirements' => ['type' => 'total_pull_requests', 'threshold' => 10],
                'sort_order' => 181,
            ],
            [
                'slug' => 'pr-50',
                'name' => 'PR Machine',
                'description' => 'Create 50 pull requests with AI',
                'category' => Badge::CATEGORY_MILESTONE,
                'tier' => 3,
                'icon' => 'code-bracket',
                'is_hidden' => false,
                'requirements' => ['type' => 'total_pull_requests', 'threshold' => 50],
                'sort_order' => 182,
            ],

            // ========================================
            // HIDDEN BADGES
            // ========================================
            [
                'slug' => 'welcome',
                'name' => 'Welcome to the Burn',
                'description' => 'Record your first coding session',
                'category' => Badge::CATEGORY_HIDDEN,
                'tier' => 1,
                'icon' => 'hand-raised',
                'is_hidden' => true,
                'requirements' => ['type' => 'total_sessions', 'threshold' => 1],
                'sort_order' => 600,
            ],
            [
                'slug' => 'first-thousand',
                'name' => 'First Thousand',
                'description' => 'Process your first 1,000 tokens',
                'category' => Badge::CATEGORY_HIDDEN,
                'tier' => 1,
                'icon' => 'sparkles',
                'is_hidden' => true,
                'requirements' => ['type' => 'total_tokens', 'threshold' => 1000],
                'sort_order' => 601,
            ],
            [
                'slug' => 'tool-master',
                'name' => 'Tool Master',
                'description' => 'Invoke 10,000 tool calls',
                'category' => Badge::CATEGORY_HIDDEN,
                'tier' => 3,
                'icon' => 'wrench',
                'is_hidden' => true,
                'requirements' => ['type' => 'total_tool_invocations', 'threshold' => 10000],
                'sort_order' => 602,
            ],
            [
                'slug' => 'marathon',
                'name' => 'Marathon Coder',
                'description' => 'Accumulate 24 hours of active coding time',
                'category' => Badge::CATEGORY_HIDDEN,
                'tier' => 3,
                'icon' => 'clock',
                'is_hidden' => true,
                'requirements' => ['type' => 'total_active_minutes', 'threshold' => 1440],
                'sort_order' => 603,
            ],
        ];

        foreach ($badges as $badgeData) {
            Badge::updateOrCreate(
                ['slug' => $badgeData['slug']],
                array_merge($badgeData, ['is_active' => true])
            );
        }
    }
}
