import { cn } from '@/lib/utils';
import {
    Tooltip,
    TooltipContent,
    TooltipTrigger,
} from '@/components/ui/tooltip';
import { HelpCircle, ExternalLink } from 'lucide-react';

type MetricType =
    | 'cache_efficiency'
    | 'cost_per_1k'
    | 'tokens'
    | 'input_tokens'
    | 'output_tokens'
    | 'cache_read'
    | 'cache_creation'
    | 'active_time'
    | 'sessions'
    | 'commits'
    | 'pull_requests'
    | 'lines_changed'
    | 'tool_invocations'
    | 'model_breakdown'
    | 'total_cost';

interface MetricInfo {
    title: string;
    description: string;
    tips?: string[];
    learnMoreUrl?: string;
    learnMoreText?: string;
}

const METRIC_INFO: Record<MetricType, MetricInfo> = {
    cache_efficiency: {
        title: 'Cache Efficiency',
        description: 'Percentage of input tokens served from Claude\'s prompt cache instead of being reprocessed. Higher efficiency = lower costs.',
        tips: [
            'Keep related work in single sessions',
            'Use consistent system prompts',
            'Avoid unnecessary context switches',
        ],
        learnMoreUrl: 'https://platform.claude.com/docs/en/build-with-claude/prompt-caching',
        learnMoreText: 'Prompt Caching Docs',
    },
    cost_per_1k: {
        title: 'Cost per 1K Output',
        description: 'Average cost to generate 1,000 output tokens. Lower values indicate more efficient model usage and better cache utilization.',
        tips: [
            'Use Haiku for simple tasks',
            'Leverage prompt caching',
            'Be specific in prompts to reduce retries',
        ],
        learnMoreUrl: 'https://www.anthropic.com/pricing',
        learnMoreText: 'Model Pricing',
    },
    tokens: {
        title: 'Total Tokens',
        description: 'Combined count of all tokens processed: input, output, cache reads, and cache creation. This is the primary metric for the leaderboard.',
        tips: [
            'Tokens include all context sent to Claude',
            'Longer conversations = more tokens',
        ],
    },
    input_tokens: {
        title: 'Input Tokens',
        description: 'Tokens sent to Claude in your prompts and context. These are charged at the input rate for your chosen model.',
    },
    output_tokens: {
        title: 'Output Tokens',
        description: 'Tokens generated by Claude in responses. Output tokens are typically more expensive than input tokens.',
    },
    cache_read: {
        title: 'Cache Read Tokens',
        description: 'Tokens served from Claude\'s prompt cache. These are significantly cheaper than regular input tokens (up to 90% savings).',
        learnMoreUrl: 'https://platform.claude.com/docs/en/build-with-claude/prompt-caching',
        learnMoreText: 'Prompt Caching',
    },
    cache_creation: {
        title: 'Cache Creation Tokens',
        description: 'Tokens written to the prompt cache for future reuse. Small upfront cost that enables significant savings on subsequent requests.',
    },
    active_time: {
        title: 'Active Time',
        description: 'Total time Claude spent actively processing requests in the CLI. This measures actual work time, not idle time.',
    },
    sessions: {
        title: 'Sessions',
        description: 'Number of Claude Code sessions started. A session begins when you run claude and ends when you exit.',
    },
    commits: {
        title: 'Commits',
        description: 'Git commits made during Claude Code sessions. Tracked automatically when Claude assists with git operations.',
    },
    pull_requests: {
        title: 'Pull Requests',
        description: 'Pull requests created or updated during Claude Code sessions.',
    },
    lines_changed: {
        title: 'Lines Changed',
        description: 'Lines of code added and removed during Claude Code sessions. Green (+) shows additions, red (-) shows deletions.',
    },
    tool_invocations: {
        title: 'Tool Invocations',
        description: 'Number of tool calls made by Claude (file reads, writes, bash commands, etc). Higher counts indicate more agentic work.',
    },
    model_breakdown: {
        title: 'Model Usage',
        description: 'Breakdown of which Claude models were used and their associated costs. Different models have different capabilities and pricing.',
        learnMoreUrl: 'https://platform.claude.com/docs/en/about-claude/models',
        learnMoreText: 'Compare Models',
    },
    total_cost: {
        title: 'Total Cost',
        description: 'Estimated API costs based on token usage and model pricing. Actual billed amounts may vary slightly.',
        learnMoreUrl: 'https://www.anthropic.com/pricing',
        learnMoreText: 'Pricing Details',
    },
};

interface MetricTooltipProps {
    metric: MetricType;
    className?: string;
    iconClassName?: string;
    side?: 'top' | 'bottom' | 'left' | 'right';
}

export function MetricTooltip({
    metric,
    className,
    iconClassName,
    side = 'top',
}: MetricTooltipProps) {
    const info = METRIC_INFO[metric];

    return (
        <Tooltip>
            <TooltipTrigger asChild>
                <button
                    type="button"
                    className={cn(
                        'inline-flex items-center justify-center opacity-40 hover:opacity-100 transition-opacity focus:outline-none focus:opacity-100',
                        className
                    )}
                    aria-label={`Learn about ${info.title}`}
                >
                    <HelpCircle className={cn('h-3.5 w-3.5', iconClassName)} />
                </button>
            </TooltipTrigger>
            <TooltipContent
                side={side}
                className="w-72 bg-popover text-popover-foreground border p-0"
            >
                <div className="p-3">
                    <div className="mb-2 font-mono text-sm font-semibold">
                        {info.title}
                    </div>
                    <p className="mb-3 text-xs leading-relaxed text-muted-foreground">
                        {info.description}
                    </p>

                    {info.tips && info.tips.length > 0 && (
                        <div className="mb-3">
                            <div className="mb-1.5 font-mono text-[10px] font-medium uppercase tracking-wider text-muted-foreground">
                                Tips
                            </div>
                            <ul className="space-y-1">
                                {info.tips.map((tip, index) => (
                                    <li key={index} className="flex items-start gap-2 text-xs text-muted-foreground">
                                        <span className="mt-1.5 h-1 w-1 flex-shrink-0 rounded-full bg-burn" />
                                        {tip}
                                    </li>
                                ))}
                            </ul>
                        </div>
                    )}

                    {info.learnMoreUrl && (
                        <a
                            href={info.learnMoreUrl}
                            target="_blank"
                            rel="noopener noreferrer"
                            className="inline-flex items-center gap-1 font-mono text-xs text-burn hover:underline"
                        >
                            {info.learnMoreText || 'Learn more'}
                            <ExternalLink className="h-3 w-3" />
                        </a>
                    )}
                </div>
            </TooltipContent>
        </Tooltip>
    );
}

// Simple inline info icon for headers
interface MetricLabelProps {
    metric: MetricType;
    label: string;
    className?: string;
    side?: 'top' | 'bottom' | 'left' | 'right';
}

export function MetricLabel({ metric, label, className, side }: MetricLabelProps) {
    return (
        <span className={cn('inline-flex items-center gap-1.5', className)}>
            {label}
            <MetricTooltip metric={metric} side={side} />
        </span>
    );
}
